# -*- coding: utf-8 -*-
"""fraud_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RwjKAwUkC7xv4BIivxC8fFJGp5tPf8N6
"""

import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import streamlit as st
import torch
import torch.nn as nn

# =========================
# Artifact path (Google Drive)
# =========================
ART_DIR = Path("/content/drive/MyDrive/Colab_Notebooks/fraud_app/results")


# =========================
# Model definition (MUST match your notebook)
# =========================
class ImprovedMLP(nn.Module):
    def __init__(self, input_dim: int):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, 256)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(128, 64)
        self.fc4 = nn.Linear(64, 32)
        self.fc5 = nn.Linear(32, 1)
        self.dropout = nn.Dropout(0.3)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.dropout(self.relu(self.fc1(x)))
        x = self.dropout(self.relu(self.fc2(x)))
        x = self.dropout(self.relu(self.fc3(x)))
        x = self.dropout(self.relu(self.fc4(x)))
        return self.fc5(x)


def mc_predict(model: nn.Module, X: torch.Tensor, T: int = 20):
    """MC Dropout prediction: returns mean probability and variance."""
    model.eval()
    for m in model.modules():
        if isinstance(m, nn.Dropout):
            m.train()

    probs = []
    with torch.no_grad():
        for _ in range(T):
            logits = model(X)
            probs.append(torch.sigmoid(logits).cpu().numpy())

    probs = np.stack(probs, axis=0)
    model.eval()
    return probs.mean(axis=0).reshape(-1), probs.var(axis=0).reshape(-1)


# =========================
# Load artifacts
# =========================
@st.cache_resource
def load_artifacts():
    if not ART_DIR.exists():
        raise FileNotFoundError(
            f"Artifact directory not found: {ART_DIR}\n"
            "In Colab, run drive.mount('/content/drive') and ensure artifacts exist in this folder."
        )

    # Required
    feature_input_cols = joblib.load(ART_DIR / "feature_input_cols.pkl")
    te = joblib.load(ART_DIR / "target_encoder.pkl")
    scaler = joblib.load(ART_DIR / "scaler.pkl")
    pca = joblib.load(ART_DIR / "pca.pkl")

    with open(ART_DIR / "target_mean.json", "r") as f:
        target_mean = json.load(f)["target_mean"]

    # Optional
    medians = {}
    medians_path = ART_DIR / "medians.json"
    if medians_path.exists():
        with open(medians_path, "r") as f:
            medians = json.load(f)

    card_stats = {}
    for card_col in ["card1", "card2", "card3"]:
        p = ART_DIR / f"{card_col}_stats.parquet"
        if p.exists():
            card_stats[card_col] = pd.read_parquet(p)

    config = {}
    config_path = ART_DIR / "config.json"
    if config_path.exists():
        with open(config_path, "r") as f:
            config = json.load(f)

    model = ImprovedMLP(input_dim=len(feature_input_cols))
    state = torch.load(ART_DIR / "mlp_state_dict.pt", map_location="cpu")
    model.load_state_dict(state)
    model.eval()

    return config, feature_input_cols, te, scaler, pca, medians, target_mean, card_stats, model


# =========================
# Preprocessing (mirrors your notebook logic)
# =========================
def preprocess_raw_to_features(
    df_raw: pd.DataFrame,
    te,
    pca,
    medians: dict,
    target_mean: float,
    card_stats: dict,
) -> pd.DataFrame:
    df = df_raw.copy()

    # Required columns
    required = ["TransactionDT", "TransactionAmt"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    # Time features
    df["TransactionHour"] = (df["TransactionDT"] // 3600) % 24
    df["TransactionDay"] = df["TransactionDT"] // (3600 * 24)
    df["TransactionDayOfWeek"] = (df["TransactionDay"] % 7)

    # Amount features
    df["TransactionAmt_log"] = np.log1p(df["TransactionAmt"])
    df["TransactionAmt_decimal"] = df["TransactionAmt"] - np.floor(df["TransactionAmt"])
    df["TransactionAmt_rounded"] = (df["TransactionAmt"] == np.round(df["TransactionAmt"])).astype(int)

    # Categorical fill
    cat_cols = ["ProductCD", "card4", "card6", "DeviceType", "P_emaildomain", "R_emaildomain", "DeviceInfo"]
    for c in cat_cols:
        if c in df.columns:
            df[c] = df[c].astype("object").fillna("missing")

    # Numeric fill using saved medians when available
    # (If your medians.json doesn't include V columns, those V NaNs will be handled below.)
    for col, med in medians.items():
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").fillna(med)

    # Target encode
    present_cat = [c for c in cat_cols if c in df.columns]
    if present_cat:
        df[present_cat] = te.transform(df[present_cat])

    # Card aggregations
    for card_col in ["card1", "card2", "card3"]:
        if card_col in df.columns and card_col in card_stats:
            stats = card_stats[card_col]
            df = df.merge(stats, on=card_col, how="left")
            df[f"{card_col}_fraud_rate"] = df[f"{card_col}_fraud_rate"].fillna(target_mean)
            df[f"{card_col}_count"] = df[f"{card_col}_count"].fillna(0)

    # PCA for V columns (expects V1..V339)
    v_cols = [c for c in df.columns if c.startswith("V")]
    if not v_cols:
        raise ValueError("No V* columns found. Upload must include V1..V339.")

    # stable order V1, V2, ...
    def v_key(c):
        try:
            return int(c[1:])
        except Exception:
            return 10**9

    v_cols = sorted(v_cols, key=v_key)

    # Fill V NaNs (fallback to 0 if not covered by medians)
    Xv_df = df[v_cols].apply(pd.to_numeric, errors="coerce")
    Xv_df = Xv_df.fillna(0.0)
    Xv = Xv_df.values.astype(np.float32)

    Xv_pca = pca.transform(Xv)
    for i in range(Xv_pca.shape[1]):
        df[f"V_pca_{i}"] = Xv_pca[:, i]

    # Drop raw V columns and raw TransactionDT (as in notebook)
    df = df.drop(columns=v_cols)
    if "TransactionDT" in df.columns:
        df = df.drop(columns=["TransactionDT"])

    return df


def align_and_scale(df_feat: pd.DataFrame, feature_input_cols: list[str], scaler) -> np.ndarray:
    # Create missing columns (safe default = 0.0)
    for c in feature_input_cols:
        if c not in df_feat.columns:
            df_feat[c] = 0.0

    X = df_feat[feature_input_cols].apply(pd.to_numeric, errors="coerce").fillna(0.0).values.astype(np.float32)
    Xs = scaler.transform(X)
    return Xs


def build_compact_output(df_raw: pd.DataFrame, probs: np.ndarray, flags: np.ndarray, var: np.ndarray | None = None):
    out = pd.DataFrame()

    # Prefer to include TransactionID (unique identifier)
    if "TransactionID" in df_raw.columns:
        out["TransactionID"] = df_raw["TransactionID"]

    # Add a small set of human-readable fields for demo (only if present)
    for c in ["TransactionDT", "TransactionAmt", "ProductCD", "card1", "card4", "DeviceType"]:
        if c in df_raw.columns:
            out[c] = df_raw[c]

    out["fraud_probability"] = probs
    if var is not None:
        out["uncertainty_variance"] = var
    out["fraud_flag"] = flags

    return out


# =========================
# UI
# =========================
st.set_page_config(page_title="Fraud Detection (CSV)", layout="wide")
st.title("Fraud Detection using Deep Learning — CSV Uploader (Compact Output)")

config, feature_input_cols, te, scaler, pca, medians, target_mean, card_stats, model = load_artifacts()

with st.sidebar:
    st.header("Options")
    use_mc = st.checkbox("Compute uncertainty (MC Dropout)", value=False)
    T = st.slider("MC samples (T)", 5, 50, int(config.get("mc_dropout_T", 20)))
    threshold = st.slider("Flag threshold", 0.0, 1.0, float(config.get("threshold", 0.5)), 0.01)
    st.caption(f"Artifacts loaded from: {ART_DIR}")

uploaded = st.file_uploader(
    "Upload CSV (must include TransactionDT, TransactionAmt, and V1..V339)",
    type=["csv"],
)

if uploaded is None:
    st.info("Upload a CSV to run predictions.")
    st.stop()

df_raw = pd.read_csv(uploaded)

# Show a small preview of input (optional)
st.subheader("Input preview")
preview_cols = [c for c in ["TransactionID", "TransactionDT", "TransactionAmt", "ProductCD", "card1", "card4", "DeviceType"] if c in df_raw.columns]
st.dataframe(df_raw[preview_cols].head(20) if preview_cols else df_raw.head(10), use_container_width=True)

try:
    # Preprocess -> align -> scale
    df_feat = preprocess_raw_to_features(df_raw, te, pca, medians, target_mean, card_stats)
    Xs = align_and_scale(df_feat, feature_input_cols, scaler)
    Xt = torch.tensor(Xs, dtype=torch.float32)

    # Predict
    if use_mc:
        probs, var = mc_predict(model, Xt, T=T)
        flags = (probs >= threshold).astype(int)
        out_compact = build_compact_output(df_raw, probs, flags, var=var)
    else:
        with torch.no_grad():
            probs = torch.sigmoid(model(Xt)).numpy().reshape(-1)
        flags = (probs >= threshold).astype(int)
        out_compact = build_compact_output(df_raw, probs, flags, var=None)

    # Display compact output
    st.subheader("Predictions (compact)")
    st.dataframe(out_compact.head(50), use_container_width=True)

    # Summary
    st.subheader("Summary")
    st.write(
        {
            "rows": int(len(out_compact)),
            "flagged": int(out_compact["fraud_flag"].sum()),
            "flagged_percent": float(100.0 * out_compact["fraud_flag"].mean()),
            "threshold": float(threshold),
        }
    )

    # Download compact CSV only
    st.download_button(
        "Download predictions CSV (compact)",
        data=out_compact.to_csv(index=False).encode("utf-8"),
        file_name="predictions_compact.csv",
        mime="text/csv",
    )

except Exception as e:
    st.error(f"Inference failed: {e}")
    st.stop()
